//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Rent_House_Project {
    
    
    public partial class Change_Secret_Question {
        
        /// <summary>
        /// Change_Secret_Question1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Modules.Change_Secret_Question Change_Secret_Question1;
    }
}
