//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Rent_House_Project.Land_load {
    
    
    public partial class Land_load_Public_Profile {
        
        /// <summary>
        /// Landload_Public_Profile_Header1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Land_load.Modules.Landload_Public_Profile_Header Landload_Public_Profile_Header1;
        
        /// <summary>
        /// HyperLinkPublicView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink HyperLinkPublicView;
        
        /// <summary>
        /// Search control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Search;
        
        /// <summary>
        /// SearchStudent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink SearchStudent;
        
        /// <summary>
        /// SearchHouse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink SearchHouse;
        
        /// <summary>
        /// LeftPanel_LandL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl LeftPanel_LandL;
        
        /// <summary>
        /// Landload_Public_Profile_Banner1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Land_load.Modules.Landload_Public_Profile_Banner Landload_Public_Profile_Banner1;
        
        /// <summary>
        /// Landload_Public_Profile_Data1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Land_load.Modules.Landload_Public_Profile_Data Landload_Public_Profile_Data1;
        
        /// <summary>
        /// Landload_Profile_Comment_Add1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Land_load.Modules.Landload_Profile_Comment_Add Landload_Profile_Comment_Add1;
        
        /// <summary>
        /// Landload_Profile_Comments1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Land_load.Modules.Landload_Public_Profile_Comments Landload_Profile_Comments1;
    }
}
