//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Rent_House_Project.Administrator {
    
    
    public partial class Property_Feature {
        
        /// <summary>
        /// PropertyFeatureAddID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Administrator.Modules.PropertyFeatureAdd PropertyFeatureAddID;
        
        /// <summary>
        /// PropertyFeatureListID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Administrator.Modules.PropertyFeatureList PropertyFeatureListID;
    }
}
