//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Rent_House_Project.Student {
    
    
    public partial class Current_House {
        
        /// <summary>
        /// Student_Profile_HeaderID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Student.Modules.Student_Profile_Header Student_Profile_HeaderID;
        
        /// <summary>
        /// Menu_Bar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Student.Modules.Menu_Bar Menu_Bar1;
        
        /// <summary>
        /// QuickLinksid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Student.Modules.Ctr_QuickLinks QuickLinksid;
        
        /// <summary>
        /// CurrentHouse1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::USA_Rent_House_Project.Student.Modules.CurrentHouse CurrentHouse1;
    }
}
